---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
        args:
        - --maxkb=25
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-json
    -   id: check-yaml
-   repo: https://github.com/bjbishop/commit_tally
    rev: 2aaad2f277c3a6076496ebbf6dd0fb0980b7d52c
    hooks:
    -   id: commit_tally
-   repo: https://github.com/bjbishop/git-secrets
    rev: a6ddf8d74bd7baae8973143553685a10131b1689
    hooks:
    -   id: git-secrets
